apiVersion: v1
kind: Pod
metadata:
  name: myapppod
  labels:
    app: myapp
spec:
  containers:
  - name: myappcontainer
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: myappsvc
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - port: 80
    targetPort: 8080
